import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <nav className="bg-blue-600 text-white p-4">
      <div className="container mx-auto flex gap-4">
        <Link href="/" className="hover:underline">Home</Link>
        <Link href="/movies" className="hover:underline">Movies</Link>
        <Link href="/actors" className="hover:underline">Actors</Link>

      </div>
    </nav>
    <main className="container mx-auto p-4">
      {children}
    </main>
    </body>
    </html>
  )
}
